version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: librarymanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "0.0.0.0:5432:5432"  # PostgreSQL - accessible from localhost and local IP
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - library-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "0.0.0.0:5288:5288"  # HTTP - accessible from localhost and local IP
      - "0.0.0.0:7291:7291"  # HTTPS - accessible from localhost and local IP
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=librarymanagement;Username=postgres;Password=admin
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - library-network

volumes:
  postgres_data:

networks:
  library-network:
    driver: bridge 